export const UPDATE_REGISTRATION_ERROR = 'UPDATE_REGISTRATION_ERROR';
export const EMAIL_IS_AVAILABLE = 'EMAIL_IS_AVAILABLE';
export const USERNAME_IS_AVAILABLE = 'USERNAME_IS_AVAILABLE';
export const UPDATE_EMAIL_AVAILABLE_ERROR = 'UPDATE_EMAIL_AVAILABLE_ERROR';
export const UPDATE_USERNAME_AVAILABLE_ERROR = 'UPDATE_USERNAME_AVAILABLE_ERROR';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
