export const UPDATE_CODE = 'UPDATE_CODE';
export const UPDATE_ACTIVATION_ERROR = 'UPDATE_ACTIVATION_ERROR';
export const UPDATE_EMAIL_AVAILABLE_ERROR_FOR_ACTIVATION =
  'UPDATE_EMAIL_AVAILABLE_ERROR_FOR_ACTIVATION';
export const ACCOUNT_ACTIVATION_SUCCESSFUL = 'ACCOUNT_ACTIVATION_SUCCESSFUL';
export const ACTIVATION_FAILED = 'ACTIVATION_FAILED';
export const ACCOUNT_ALREADY_ACTIVE = 'ACCOUNT_ALREADY_ACTIVE';
export const RESEND_ACTIVATION_CODE_RESULT = 'RESEND_ACTIVATION_CODE_RESULT';
